create table if not exists public.rsvps (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  organisation text not null,
  position text not null,
  email text not null unique,
  attendance text not null check (attendance in ('attending', 'not_attending')),
  dietary text,
  accessibility text,
  notes text,
  language text not null check (language in ('tr', 'en')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.rsvps enable row level security;
